### ISSUE TITLE
Getting multiple "Select IDB" prompts when opening a BNDB

### ISSUE THREAD

**Issue by alexrp** [Vector35/idb-import-plugin#2] opened 2022-06-09 09:14 UTC
After updating to 3.1.3494-dev, I'm suddenly getting multiple "Select IDB" prompts while opening a BNDB. I'm assuming those are coming from this plugin.

I do have an IDB for the same executable next to the BNDB because I occasionally need to check how IDA handles some things. Could the plugin be detecting that and assuming I want to import it or something?

**Comment by rose4096** [comment] 2022-06-09 14:58
Do you have a screenshot of this popup? Also what does the file structure look like?

I wasn't able to repro this with a .i64, .bndb. and the original file all in the same directory when opening either the .bndb or the file itself.

**Comment by alexrp** [comment] 2022-06-09 15:16
(Also, I confirmed that disabling this plugin gets rid of those prompts.)

**Comment by fuzyll** [comment] 2022-06-09 16:17
I'm trying to reproduce this locally on Windows 11 with 3.1.394-dev and...I cannot. 😞

Here's the files I'm working with:

```
notepad.bndb
notepad.exe.til
notepad.exe.i64
notepad.exe
```

I opened `notepad.exe` initially and created `notepad.bndb`, then re-opened `notepad.bndb` and neither triggered any prompts. I did get an unrelated crash when trying to apply the types from the TIL and IDB that we're aware of, but I was unable to get the prompts to show up without manually going to Tools -> Plugins -> IDB (Beta) and selecting one of the "Import..." options.

You are 100% correct that the prompts have to be coming from this plugin, but we're pretty baffled as to how they're showing up automatically for you. Are you running any other plugins that could possibly be interacting with this one in a way we didn't expect? Or are there any other changes you've made to the environment you're running in that could help us track this down?

**Comment by alexrp** [comment] 2022-06-09 17:48
I just tried again with all non-core plugins disabled and it no longer happens, so it seems there's a weird interaction happening here. I'll try to narrow it down...

**Comment by fuzyll** [comment] 2022-06-09 19:25
It might? I'm still pretty confused as to how this would happen, though.

If you look at the plugin source, there are two `command`s and two `DebugInfoParser`s that are `register`ed when the plugin starts: https://github.com/Vector35/idb-import-plugin/blob/main/src/lib.rs#L468. The `command`s are what's placed in the Tools -> Plugins -> IDB (Beta) menu and they'll look up the `DebugInfoParser`s so they can do the parsing for each filetype.

The file dialogs that you're seeing are part of the `parse_info` function for each (like here: https://github.com/Vector35/idb-import-plugin/blob/main/src/lib.rs#L392). Because the `DebugInfoParser` has been registered separately from the `command`, it's entirely possible that some other code is looking it up and calling it multiple times when you load the binary. But, we're not seeing code that does that in our core.

Also, as far as we're aware, there shouldn't be anything registered as a "go run this `DebugInfoParser` if you see a `.til` in the local directory" kind of thing. So, we truly are confused...

**Comment by alexrp** [comment] 2022-06-09 19:48
> I'm still pretty confused as to how this would happen, though.

Same here, fwiw. I took a look at the code before filing the issue and I'm just as confused as you are...

> EDIT: When you say you're trying with no plugins, how are you doing that?

I wasn't aware of `BN_DISABLE_USER_PLUGINS`; I just removed the `plugins` directory from my BN user directory.

**Comment by fuzyll** [comment] 2022-06-09 19:49
Your comment in a completely different issue I believe has uncovered the culprit! Can you try disabling `analysis.experimental.parseDebugInfo` and confirm that the issue goes away? From a discussion we're having internally, we believe that this plugin is basically broken when that's turned on.

**Comment by rose4096** [comment] 2022-06-09 21:12
This should be fixed in version ≥ 3.1.3497.

**Closed by rose4096** 2022-06-09 21:12 UTC

**Comment by alexrp** [comment] 2022-06-10 11:30
Just updated and can confirm the issue is fixed.
